id: f9a904ad-d16e-403d-b799-680c69ad4258
title: 60fps Static
subtitle:
description:
version: 3.0.2
category: 1
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.0
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
    - c3b36da0-67f4-4ffe-8b94-6293494fb90a
author:
  - { name: 'ChucksFeedAndSeed, patchanon, somerandompeople, ActualMandM and StevenssND', link: }

